CREATE DATABASE IF NOT EXISTS NetMeTube;

use NetMeTube;
CREATE TABLE IF NOT EXISTS users (
	user_id BINARY(16) PRIMARY KEY,
    user_email VARCHAR(255) UNIQUE NOT NULL,
	username VARCHAR(36) NOT NULL,	
	user_password VARCHAR(72) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

